[package]
name = "vulkan_experinments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
ash = "0.37.0+1.3.209"
ash-window = "0.10.0"
gpu-allocator = "0.18.0"
winit = "0.26.1"